#! /usr/bin/env node
let yargs = require('yargs')
// 他可以帮我们解析命令行参数, 把参数数组变成对象的形式
let argv = yargs.options('n', {
  alia: 'name',
  demand: true,
  default: 'zfpx',
  description: '请输入您的姓名'
}).usage('hello [options]')
.help()
.example('hello -name zfpx', '执行hello命令, 然后传入那么参数')
.alia('h','help')
.argv;
console.log(argv)